### ISSUE TITLE
List of Collections

### ISSUE THREAD

**Issue by matfur92** [Danappelxx/SwiftMongoDB#1]
Hi, I would connect my mongodb directly to my iPhone to explore every collection and add/edit/remove every document.
I can't find a method to have a list of databases and collections.
I would have a method that have the same role as
- show databases
- show collections
  It's possible?
  Thanks in advance
  Matteo

**Comment by Danappelxx** [comment]
This is definitely possible (as shown [here](http://stackoverflow.com/questions/8286994/how-can-i-get-a-list-of-databases-and-collections-on-a-mongodb-server)) - I'll look into it. Unfortunately I'm working on migrating to a newer version of the mongo c driver which is almost a complete rewrite. Hopefully I'll have a working version you can use in a few days.

**Comment by matfur92** [comment]
Thanks for the answer, it is great news!
I await your news regarding the new library version;)
The application that I'm going to create will use your library and will obviously be open source on github.
Thanks again, Matteo

PS: I think the ability to insert commands into generic format B / JSON is the best option. In this way you could generate all commands, even those not yet encapsulated in some class.

**Comment by Danappelxx** [comment]
It's neat that you want to use swiftmongodb! If you have any more issues I'll be glad to help you out.

Regarding your note about directly inserting json - it actually makes it easier for me since libbson supports it. In fact, I'm thinking about completely adding SwiftyJSON as a dependency to make this built-in so that there will be minimal work to be done on my part.

**Comment by matfur92** [comment]
I think it's a good idea to add SwiftyJSON! Little work and huge benefits
The new version to which you're working, will support MongoDB 3.0?

**Comment by Danappelxx** [comment]
Yup! The compatibility table can be found [here](http://docs.mongodb.org/ecosystem/drivers/c/).

**Comment by matfur92** [comment]
Fantastic!

**Comment by Danappelxx** [comment]
Just implemented getDatabaseNames() and getCollectionNamesInDatabase() on the branch 'mongoc-migrate' at the commit 0e816cca2d36e9173ed828b9df125e265c528fa4. Not on an official release unfortunately due to some cocoapod issues, but that'll come soon!

**Comment by matfur92** [comment]
Hi @Danappelxx ! 
I saw that you're doing a fantastic job with the library !
Finally I'm able to devote myself to the development of the application . It's possible to have the latest version of the library on CocoaPods or it's better that I copy it manually in my project?
Thanks in advance,
Matteo

**Comment by Danappelxx** [comment]
Hi! Unfortunately development has kind of stalled while I try to figure out how to package mongoc in a way that actually works for everyone. Your best shot would be to clone the project, pod install, and attempt to build it, but I'm not sure if the way it is setup right now will work on all machines.

**Comment by matfur92** [comment]
In my pod file I've written:
`pod 'SwiftMongoDB', :git => 'https://github.com/Danappelxx/SwiftMongoDB.git'`
but at compile time I have this error:
`/dependencies/mongoc/mongoc-server-description.h:22:10: 'mongoc-array-private.h' file not found`
In the pod-tree-directory this file isn't present.
This could help you to fix the error?

<img width="1013" alt="swiftmongodb_0_2_0_tree" src="https://cloud.githubusercontent.com/assets/10245779/10363134/00bf9494-6db3-11e5-93d4-fef23ba79e99.png">

**Comment by matfur92** [comment]
I've found in https://github.com/jeromelebel/MongoObjCDriver a configuration for pod:
https://github.com/jeromelebel/MongoObjCDriver/blob/master/MongoObjCDriver.podspec

The idea is to use a submodule and reference it as local directory/source file as it has done in the MongoObjCDriver.podspec linked.

To use a submodule you can find a guide/example at http://stackoverflow.com/questions/2140985/how-to-set-up-a-git-project-to-use-an-external-repo-submodule .

Tell me if I have crazy ideas or may work ;)

**Comment by Danappelxx** [comment]
That's definitely something I haven't considered yet - great idea. By the way, the `mongoc-array-private.h not found` is due to a typo in the podspec - check out issue #2. My solution is to wait for mongodb to fix their podspec - they're working on it right now. Check out [this issue on their jira](https://jira.mongodb.org/browse/CDRIVER-691).

Thanks for the suggestion, though!

**Comment by matfur92** [comment]
I've seen this https://github.com/paulmelnikow/mongo-c-driver-1/blob/1.1.11%2Bpodspec/mongo-c-driver.podspec , but if you use submodule linked to mongoc repo, podspec in mongoc isn't a problem, you must import the static library, I think.
In Jira I've seen `Resolution: Won't Fix` and `Status: Closed` are you sure that they're working on it right now?

**Comment by Danappelxx** [comment]
Oh, I see what you mean. I'll try it out - very clever alternative. I'm worried about the fact that you can't use static libraries in swift though (have to use frameworks), but I'll see how it goes first.

Regarding the issue - if you read through the comments, you can see that it was originally closed (a while ago) due to the maintainers not knowing how to work with cocoapods. However, they found they guy who managed it for them when I asked and the changes he's making are pretty promising.

**Comment by matfur92** [comment]
Hi! One of my friends suggested a workaround to have swiftMongoDB functioning. Here are the steps

Open workspace
1. remove use_frameworks! from PodFile
2. add `pod 'mongo-c-driver'` on Podfile and run pod install
3. add 2 new module (cocoa framework). One for SwiftyJSON e one for
   swiftMongoDB
4. copy in files of this pods and add (dragging) in Xcode

In MongoDBManager (Name of main project):
1. in swiftMongoDB add on General > Linked Frameworks and Libraries :
   `"SwiftyJSON.framework" and "libPods-MongoDBManager.a"`
2. Add on swiftMongoDB > Build Settings > Other Linked Flags this string:
   `-l"libbson" -l"mongo-c-driver"` 
3. Add on swiftMongoDB > Build Settings > Objective-C Bridging Header this string:
   `swiftMongoDB/swiftMongoDB-Bridging-Header.h`   
4. Add on swiftMongoDB > Build Settings > Header Search Paths this strings:
   `"${SRCROOT}/Pods/Headers/Public/libbson/bson"` 
   
   `"${SRCROOT}/Pods/Headers/Public/mongo-c-driver/mongoc"` 

In Pods subproject: > mongo-c-driver > Build Settings > Header Search Paths add another line :
 `"${PODS_ROOT}/Headers/Public/libbson/bson"`  

I know this is not the solution for cocoapods but I posted in the event was useful for someone until you find a solution.

As for the issue static libraries I think I understand what you mean. I do not know if it can be helpful, but I found this link : https://github.com/hpique/Talks/blob/master/Building%20Swift%20frameworks/Building%20Swift%20frameworks.md .

**Comment by matfur92** [comment]
To have a SCRAM-SHA-1 I need of OpenSSL. To have this I hade done following steps.

Add a personalized version of mongo-c-driver that have a different compile flag. 
I copied in local https://github.com/paulmelnikow/mongo-c-driver-1 downloading the zip. and change in `mongo-c-driver.podspec` --enable-ssl=no to`--enable-ssl=yes` to enable OpenSSL. 
Then I link the directory that contains the "forked version" on the Podfile using `pod 'mongo-c-driver', :path => 'mongo-c-driver-1-1.1.11-podspec'`

Add to PodFile OpenSSL-for-iOS (1.0.2.d.1) cocoapod with:
`pod 'OpenSSL-for-iOS', '1.0.2.d.1'`
and run `pod install` that install OpenSSL on project.

In Pods subproject: > mongo-c-driver > Build Settings > Header Search Paths add another line :
`"${PODS_ROOT}/Headers/Public/libbson/bson"`

In main project properties (MongoDBManager) select `swiftMongoDB` target and add new “Linked Frameworks and Libraries” and select `openssl.framework` that is located in Pods > OpenSSL-for-iOS directory.

**Comment by Danappelxx** [comment]
Sorry I took so long to respond - I've been busy the past few days :)

Regarding your work for dependencies - jeez that is a _lot_ of work, pat yourself on the back for me :). Now people can actually use it if they _really_ want to, which is great.

Regarding the work you did with OpenSSL - I was recommended to wait for official support from MongoDB (they are working on it) since OpenSSL is actually deprecated on OS X and not available on iOS. Take a look at the reasoning [here](https://jira.mongodb.org/browse/CDRIVER-691?focusedCommentId=1050621&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1050621).

 I thought I said this earlier but I guess I didn't - here's how I got dependencies to work (not much simpler than what you offered):

###### Setup MongoC
1. Clone the [mongo-c-driver repository](https://github.com/mongodb/mongo-c-driver/).
2. Run `./autogen.sh` to generate the makefile.
3. Run `./configure --with-libbson=no --enable-ssl=no --enable-sasl=no` without ssl because OpenSSL is deprecated on OS X (more about this earlier in the comment).
4. Run `make && sudo make install` to build & install mongoc.

###### Implement it into SwiftMongoDB
1. Look for compiled static libraries `libbson` and `libmongoc` in `/usr/local/lib`:

``` bash
$ ls /usr/local/lib | grep -i 'bson\|mongoc'
libbson-1.0.0.dylib
libbson-1.0.dylib
libbson-1.0.la
libmongoc-1.0.0.dylib
libmongoc-1.0.dylib
libmongoc-1.0.la
libmongoc-priv.0.dylib
libmongoc-priv.dylib
libmongoc-priv.la
```
1. Take `libbson-1.0.0.dylib` and `libmongoc-1.0.0.dylib` and copy them into `swiftMongoDB/dependencies`, replacing the ones that are currently there.
2. Add `$(PROJECT_DIR)/swiftMongoDB/dependencies` to your `Library Search Paths` in the Xcode project.

You might be done here - try building the project. If it still doesn't work, there's a chance that the headers currently in the project are different from the ones you generated.
1. Search for `libbson` and `libmongoc` headers in `/usr/local/include`. I found `/usr/local/include/libmongoc-1.0` and `/usr/local/include/libbson-1.0` with lots of headers inside of them.
2. Replace the headers in `swiftMongoDB/dependencies/{mongoc,bson,private}` with the respectful headers in `usr/local/include` (where private is anything ending with -private.h).
3. Drag the new dependencies folder into the Xcode project and set _all_ the new headers to be public.

You're (hopefully) done! The project should now build without any issues.

BTW, this probably belongs in #2 rather than here :)

Thanks for your help!

**Comment by matfur92** [comment]
Don't worry, thanks to you for the work you have already done;) 
Thanks for the guide, I was wondering where those .dylib appeared : D
Regarding OpenSSL I need to have the support now, so I think I will stay still to my "version" because is working. When there will be news from MongoDB I will proceed to change what is need.
